# Macro file for the initialization of example B1
# in interactive session
#
# Set some default verbose
/control/verbose 2
#/control/saveHistory
/run/verbose 2
#
# Create a standard drawing model for your trajectories
/vis/modeling/trajectories/create/drawByCharge
/vis/modeling/trajectories/drawByCharge-0/default/setDrawStepPts true
/vis/modeling/trajectories/drawByCharge-0/default/setStepPtsSize 2
#
