/run/initialize
#This file will allow arbitrary number of source, types of particles, at arbitrary intensities.
#
#Allow CSV to save.
#
/QR/output/writeSteps true
/QR/output/writeAllEvents true
/QR/output/addNtuple full full
#
#Draw Visual
#
/vis/open OGLSQt 600x600-0+0
/vis/drawVolume
/vis/viewer/zoom 10
/vis/viewer/set/viewpointThetaPhi 70 30
/vis/scene/add/trajectories smooth
/vis/scene/endOfEventAction accumulate 10
#
#Below add augmented data
