#!/usr/bin/env python3
import os
import sys
import shutil
import glob
from datetime import datetime

def parse_macro_for_particles(macro_path):
    """Parses the macro file to count unique particle types used."""
    if not os.path.exists(macro_path):
        print(f"Error: Macro file not found at {macro_path}")
        return 0, "unknown"
    
    particles = set()
    with open(macro_path, 'r') as f:
        for line in f:
            line = line.strip()
            # Look for active GPS particle definitions, ignoring comments
            if line.startswith("/gps/particle"):
                parts = line.split()
                if len(parts) >= 2:
                    particles.add(parts[1])
                    
    num_types = len(particles)
    if num_types == 0:
        return 0, "none"
        
    # Join particle names with underscores (e.g., 'neutron_proton')
    particle_str = "_".join(sorted(list(particles)))
    return num_types, particle_str

def main():
    # --- 1. Validate Command Line Arguments ---
    if len(sys.argv) < 2:
        print("Error: Missing distribution type variable.")
        print("Usage: python3 scripts/sort_sim_data.py <test_hist|ISO_spectrum|mono> [macro_path]")
        sys.exit(1)
        
    dist_type = sys.argv[1]
    if dist_type not in ["test_hist", "ISO_spectrum", "mono"]:
        print(f"Warning: Unexpected distribution type '{dist_type}' provided.")

    # --- 2. Gather Dynamic Information ---
    macro_file = sys.argv[2] if len(sys.argv) >= 3 else "macros/gps_single_neutron_test.mac"
    num_particles, particle_names = parse_macro_for_particles(macro_file)
    
    # Generate date token formatted as Month/Day_HourMinute (e.g., 06_22_1327)
    # Note: Using underscores instead of slashes/colons to keep file system paths clean
    date_str = datetime.now().strftime("%m_%d_%H%M")
    
    # --- 3. Determine the Specific Run Number ---
    base_data_dir = "./output/Data"
    if not os.path.exists(base_data_dir):
        os.makedirs(base_data_dir)
        
    # Check existing directories to find the next available sequential Run number
    existing_runs = glob.glob(os.path.join(base_data_dir, "Run_*"))
    run_num = 1
    if existing_runs:
        run_indices = []
        for path in existing_runs:
            folder_name = os.path.basename(path)
            try:
                # Extract the number right after 'Run_'
                num = int(folder_name.split("_")[1])
                run_indices.append(num)
            except (IndexError, ValueError):
                continue
        if run_indices:
            run_num = max(run_indices) + 1

    # --- 4. Construct Target Folder Hierarchy ---
    # Target string template: Run_{#}_{#Particle Types}_{Particle types}_{Distribution type}_{date}
    run_folder_name = f"Run_{run_num}_{num_particles}_{particle_names}_{dist_type}_{date_str}"
    run_dir = os.path.join(base_data_dir, run_folder_name)
    
    metadata_dir = os.path.join(run_dir, "Metadata")
    rawdata_dir = os.path.join(run_dir, "Rawdata")
    
    # Create the complete nested directory path safely
    os.makedirs(metadata_dir, exist_ok=True)
    os.makedirs(rawdata_dir, exist_ok=True)
    print(f"Created target directory system: {run_dir}")

    # --- 5. Sort and Move CSV and JSON files ---
    # Find files matching 'test*' pattern generated by Geant4
    csv_files = glob.glob("test*.csv")
    json_files = glob.glob("test*.json")
    
    moved_csv_count = 0
    for file_path in csv_files:
        shutil.move(file_path, os.path.join(rawdata_dir, os.path.basename(file_path)))
        moved_csv_count += 1
        
    moved_json_count = 0
    for file_path in json_files:
        shutil.move(file_path, os.path.join(metadata_dir, os.path.basename(file_path)))
        moved_json_count += 1

    print(f"Sorting Complete: Moved {moved_csv_count} CSVs to Rawdata and {moved_json_count} JSONs to Metadata.")

if __name__ == "__main__":
    main()
