# Macro file for the initialization of example B1
# in interactive session
#
# Set some default verbose
/control/verbose 2
#/control/saveHistory
/run/verbose 2
#
# Create a standard drawing model for your trajectories
/vis/modeling/trajectories/create/drawByParticleID customDrawByParticle 
/vis/modeling/trajectories/customDrawByParticle/set neutron yellow 
/vis/modeling/trajectories/customDrawByParticle/set gamma cyan 
/vis/modeling/trajectories/customDrawByParticle/set e- red 
/vis/modeling/trajectories/customDrawByParticle/set geantino magenta 
/vis/modeling/trajectories/customDrawByParticle/set proton blue 
/vis/modeling/trajectories/select customDrawByParticle 


/QR/output/writeSteps true
/QR/output/writeAllEvents true
/QR/output/addNtuple full full
/run/initialize
/control/execute /Users/tclassen23/q-array-g4/build-dspx/temporary_multi_source.mac
